### ISSUE TITLE
Fix problem with Flycheck > 0.21

### ISSUE THREAD

**Issue by mgudemann** [flycheck/flycheck-mercury#3]
`flycheck-mercury` does not work correctly with newer versions of Flycheck. There is no error report for the checker but no warnings or errors are reported. A git-bisect pointed to commit flycheck/flycheck@0cd00c6e9334127b6d3d31a439d4b524979bfbe5 which marks the begin of the generic syntax checker integration.

**Comment by lunaryorn** [comment]
@mgudemann Iirc this syntax checker has a custom error parser, has it not?  In this case, you now need to set explicitly set the `:filename` and `:buffer` slots of `flycheck-error` objects.

**Comment by mgudemann** [comment]
@lunaryorn thank you for the info, must have missed this, I'll adapt the checker.

Sorry for the comment for the other issue, but it sounded like exactly the same behaviour (checker not flawed, flycheck-compile working, but no errors reported)

**Comment by lunaryorn** [comment]
@mgudemann Never mind.  The symptoms were indeed the same, so you were right to join that issue.  I would have missed this one, had you not commented.
